// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var init, ready;

  ready = function(fn) {
    if (document.readyState !== 'loading') {
      return fn();
    } else {
      return document.addEventListener('DOMContentLoaded', fn);
    }
  };

  init = function() {
    return console.log("%c Welcome fellow DOM traveler!", "color: #f7a73c;");
  };

  ready(init);

}).call(this);
