// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var consoleEasterEgg, getRandomInt, init, mobileBrowser, ready, themes;

  ready = function(fn) {
    if (document.readyState !== 'loading') {
      return fn();
    } else {
      return document.addEventListener('DOMContentLoaded', fn);
    }
  };

  mobileBrowser = window.innerWidth <= 800;

  getRandomInt = function(min, max) {
    return Math.floor(Math.random() * (max - min)) + min;
  };

  themes = [
    {
      image: 'tree.jpg',
      color: '#00C2AF',
      titleColor: '#174044'
    }, {
      image: 'retro-pop.jpg',
      color: '#ef9c19',
      titleColor: '#1c1f3b'
    }, {
      image: 'bridge.jpg',
      color: '#10d074',
      titleColor: '#dbfcef'
    }, {
      image: 'cat.jpg',
      color: '#ef02a2',
      titleColor: '#85065c'
    }, {
      image: 'city-nights.jpg',
      color: '#f7a73c',
      titleColor: '#ffefd8'
    }, {
      image: 'foggy.jpg',
      color: '#a4d643',
      titleColor: '#e9e3d8'
    }, {
      image: 'nebula.jpg',
      color: '#e8bc4b',
      titleColor: '#f5f1eb'
    }, {
      image: 'neon-sign.jpg',
      color: '#ef349d',
      titleColor: '#fff'
    }, {
      image: 'space-ship.jpg',
      color: '#7fb676',
      titleColor: '#f6ffe2'
    }, {
      image: 'sleeping-cat.jpg',
      color: '#f3a11b',
      titleColor: '#fff'
    }, {
      image: 'tiddly-winks.jpg',
      color: '#c1201c',
      titleColor: '#fff'
    }, {
      image: 'typewriter.jpg',
      color: '#e42f11',
      titleColor: '#060606'
    }
  ];

  consoleEasterEgg = function(color) {
    return console.log("%c Welcome fellow DOM traveler!", "color: #f7a73c;");
  };

  init = function() {
    return consoleEasterEgg(color);
  };

  ready(init);

}).call(this);
