name: Adam Waselnuk - Web Developer
url: http://www.adamwaselnuk.com
author: Adam Waselnuk
description: >
    Articles about web development and working in the tech industry by Adam Waselnuk.
    I’m a web developer who cares deeply about interaction design, writing software, and programming literacy for everyone.
highlighter: rouge
exclude: ["node_modules", "package.json"]
