name: Adam Waselnuk
url: https://www.adamwaselnuk.com
author: Adam Waselnuk
description: >
  Articles about bootstrapping a business in tech and web development by Adam Waselnuk.
  I’m a first-time founder who is bootstrapping a software business. Follow along as I learn!
highlighter: rouge
exclude: ["node_modules", "package.json"]
