name: Adam Waselnuk - Front End Developer
url: http://www.adamwaselnuk.com
highlighter: pygments # or rouge or null
exclude: ["node_modules", "package.json"]
collections:
  projects:
    output: true
  experiments:
    output: true
